import asyncio
import base64
import json
import os
from typing import Any
from pprint import pprint
from bs4 import BeautifulSoup
from starlette.middleware.cors import CORSMiddleware

from src.types import InvoiceLanguage, JSON, Headers
from src.API.StrapiFillDataBaseAPI import fill_all_tables
from src.Requests.Request_strapi import get_by_id_from_strapi
from src.Strapi.manage_Invoice_from_Strapi import get_template_from_strapi
from src.Invoice_Generator import InvoiceGenerator
from src.Datenvalidierung.Pydantic_Classes import Invoice_language
from src.Datenvalidierung.Enum_Classes import Type_Invoice_language
from dotenv import load_dotenv
import requests
from starlette.responses import HTMLResponse
from io import BytesIO
from src.PDF_Processing.HtmlToTemplateConverter import HtmlToTemplateConverter
from src.PDF_Processing.LTItemsExtractor import LTItemExtractor
from src.PDF_Processing.LTItemsToHtmlConverter import LTItemsToHtmlConverter
from fastapi import FastAPI, File, UploadFile, Form
from src.document_generator_python_backend.src.TemplateModifier import TemplateModifier
from src.utility.gpt_prompts_storage import Template_Modifier_Prompt
from src.utility.html_placeholders import HTMLPlaceholders
from src.utility.html_placeholders_frontend import HTMLPlaceholders_frontend
from src.Strapi.Invoice_Adapter import Invoice_Adpater
from src.PDF_Processing.HtmlConfigurator import HtmlConfigurator
from src.utility.strapi_endpoints import (
    STRAPI_PDFINVOICE_ENDP,
    STRAPI_TEMPLATE_ENDP,
    STRAPI_COUNT_ENDP,
    STRAPI_COMPANY_ENDP,
)
from src.utility.strapi_specified_filters import STRAPI_ONLY_URL_OF_PDF_FILTER
from src.API.AugmentationAPI import router as augmentation_router
from src.API.DatasetAPI import router as dataset_router

load_dotenv()

"""
    Gedankenhilfe : mit cd in root directory und dann 
    --> uvicorn src.API.DocumentGenAPI:app --reload --host 127.0.0.1 --port 8000
    8000 erstmal in .env als BASE_UVICORN_URL_DOCUMENT = "http://127.0.0.1:8000" festgelegt
"""
app = FastAPI()

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # List of allowed origins
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods
    allow_headers=["*"],  # Allows all headers
)

# Include routers
app.include_router(augmentation_router)
app.include_router(dataset_router)


@app.get("/", response_class=HTMLResponse)
def read_root() -> str:
    """Root endpoint providing API information."""
    multi_string = """docgen-python-backend:
                      Main usage via docgen-workbench
                       """
    return f"<html><body><pre>{multi_string}</pre></body></html>"


@app.get("/pre_fill_strapi")
async def pre_fill_strapi() -> None:
    """
    Pre-fills the strapi database with data needed to execute /create_invoice successfully.
    It also pushes the latest templates to the database.
    Last Template check: 21.08.2024.
    To make sure that the templates are up-to-date refer to
    fill_template_with_current_templates() in src/API/StrapiFillDataBaseAPI.py
    """
    fill_all_tables()


@app.get("/create_invoice")
async def create_invoice(
    openai_key: str,
    bearer_token: str,
    language_of_invoice: str | Invoice_language = "de",
    model: str = "gpt-5.1",  # Alle Aufrufe nutzen jetzt GPT-5.1
    product_count: int = 10,
    temperature: float = 0.8,  # Für GPT-5.1 ist 0.8 optimal
    time_limit: int = 30000,
    all_content_with_llm: bool = False,
    seller_name_fictional: bool = True,
) -> JSON:
    """
    Creates the data for an invoice with the help of a LLM.
    :param bearer_token: Strapi bearer token
    :param openai_key: OpenAI key for function calling
    :param model: Name of the 'standard' LLM with which all questions are to be answered.
    :param temperature: Temperature that the LLM should have. The value 0.0 is useful for creating invoices.
    :param product_count: Number of products to be generated.
    :param time_limit: Specifies the time limit that applies to the generation of each product. An error is thrown if
                       this is exceeded.
    :param language_of_invoice: Language in which the invoice should be in. Is regulated by the fact that the language
                                of the prompts is defined by specifying the language. This then automatically leads to
                                the LLM also responding in the  respective language.
    :param seller_name_fictional: Boolean parameter that decides whether the seller is given a fictitious name by a
                                  request to the LLM.
    :param all_content_with_llm: Boolean value that determines whether the extra information such as date etc. should
                                 also be generated by the LLM. It does not currently make sense to generate everything
                                 with the LLM. Higher costs, higher inference time and sometimes worse results than if
                                 the extra information is taken from a database or generated by normal Python
                                 functions, such as the date.
    :return: dict with all the information of an invoice that can be pushed to Strapi. Return is intended to be used
             in Invoice_adapter.py as instance variable data of an adapter.
             adapter1 = Invoice_Adapter(data=data,
                               html_template_data=[html_template, html_template_id, html_template_product_count],
                               html_placeholder=HTML_Placeholders, bearer_token=BEARER_TOKEN)
    """

    if get_by_id_from_strapi(
        endpoint=STRAPI_COMPANY_ENDP + STRAPI_COUNT_ENDP,
        bearer_token=os.getenv("STRAPI_BEARER_TOKEN"),
    ) == 0 or isinstance(
        get_by_id_from_strapi(
            endpoint=STRAPI_COMPANY_ENDP + STRAPI_COUNT_ENDP,
            bearer_token=os.getenv("STRAPI_BEARER_TOKEN"),
        ),
        dict,
    ):
        """Soll man hier alle 6 Möglichkeiten testen? tendenziell könnte ja beim füllen ein Problem aufgetreten sein. 
           Check dauert dann halt 6 mal so lange
            STRAPI_SURNAME_ENDP = "/api/surnames"
            STRAPI_M_FIRSTNAME_ENDP = "/api/malefirstnames"
            STRAPI_W_FIRSTNAME_ENDP = "/api/femalefirstnames"
            STRAPI_CITY_ENDP = "/api/cities"
            STRAPI_STREET_ENDP = "/api/streets"
            STRAPI_COMPANY_ENDP = "/api/companies"
        """
        fill_all_tables()

    if not any(member.value == language_of_invoice for member in Type_Invoice_language):
        raise ValueError(
            print(
                f"language_of_invoice must be one of the following: {[member.value for member in Type_Invoice_language]}"
            )
        )
    generator: InvoiceGenerator = InvoiceGenerator(
        model=model,
        temperature=temperature,
        product_count=product_count,
        time_limit=time_limit,
        invoice_lang=language_of_invoice,
        openai_key=openai_key,
        bearer_token=bearer_token,
    )
    invoice: dict = generator.generate_invoice_data(
        w_fict_company=seller_name_fictional, all_content_w_llm=all_content_with_llm
    )
    return invoice


@app.get("/post_invoice_data_to_strapi")
async def post_invoice_data(invoice_data: JSON, bearer_token: str) -> JSON:
    """
    Post invoice data to Strapi and get back the id where its stored.
    :param invoice_data: invoice data to be posted to Strapi
    :param bearer_token: Strapi bearer token
    :return: ID of the invoice entry in which the data is stored.
    """
    try:
        adapter: Invoice_Adpater = Invoice_Adpater(data=invoice_data, bearer_token=bearer_token)

        created_invoice_id: int = adapter.post_all_available_data()
        return {"invoice_id": created_invoice_id}
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return {"error": str(e)}


@app.post("/get_pdf_from_strapi")
async def get_pdf_from_strapi(
    pdf_invoice_id: int = Form(...),
    bearer_token: str = Form(...),
    only_url: str = Form(...),
) -> JSON:
    """
    Get the pdf (as base 64 string) or the URL of a specific pdf_invoice entry (specified by the id)
    :param pdf_invoice_id: ID of the pdf_invoice entry
    :param bearer_token: Strapi bearer token
    :param only_url: If true only the url is given back. If False the  base64 string of the PDF is given back
    :return: Return either the URL or the base 64 string of the pdf, stored in Strapi within the pdf_invoice enrty with
             id: pdf_invoice_id
    """
    only_url: bool = only_url.lower() == "true"  # erzeugt true oder false aus dem string input
    response: dict = get_by_id_from_strapi(
        endpoint=STRAPI_PDFINVOICE_ENDP,
        bearer_token=bearer_token,
        entry_id=pdf_invoice_id,
        add_filter=STRAPI_ONLY_URL_OF_PDF_FILTER,
    )
    pdf_url = response["data"]["attributes"]["pdf"]["data"]["attributes"]["url"]
    if only_url:
        return {
            "url_to_pdf": os.getenv("STRAPI_URL") + pdf_url
        }  # ist ganze URL also Strapi + spezifische pdf URL
    else:
        # So weil er mich den requests.get(url=os.getenv("STRAPI_URL") + pdf_url).content nicht in den dict hat
        # schreiben lassen. Wollte immer decoden (Pydantic?).
        # UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 68: invalid continuation byte
        # data = Response(content=requests.get(url=os.getenv("STRAPI_URL") + pdf_url).content)
        data = requests.get(url=os.getenv("STRAPI_URL") + pdf_url).content
        pdf_base64 = base64.b64encode(data).decode("utf-8")
        return {"PDF": pdf_base64}


@app.post("/get_pdf_from_strapi_via_url")
async def get_pdf_from_strapi_via_url(pdf_url: str = Form(...)) -> JSON:
    """
    Retrieve the pdf of given URL from Strapi.

    :param pdf_url: URL of the PDF
    :return: PDF as base64 string
    """
    data = requests.get(url=os.getenv("STRAPI_URL") + pdf_url).content
    pdf_base64 = base64.b64encode(data).decode("utf-8")
    return {"PDF": pdf_base64}


@app.post("/create_pdf_invoice_entry")
async def create_pdf_invoice_entry(
    invoices_used: str = Form(...),
    bearer_token: str = Form(...),
    templates_used: str = Form(...),
    specific_product_nums: str = Form(...),
    languages_used: str = Form(...),
) -> JSON:
    """

    :param languages_used: Number of languages used
    :param invoices_used: Number of invoice data used
    :param templates_used: Number of templates used
    :param specific_product_nums: Number of products allowed in the invoices
    :param bearer_token: Strapi bearer token
    :return:

    """
    # if template_id == 0:
    #     """ERSTMAL NICHT NUTZEN MUSS NOCH UMGEBAUT WERDEN FÜR DEN NEUEN ANSATZ MIT DEN 10 PRODUKTEN"""
    #
    #     """Wird gemacht um product count zu bekommen wird nicht mehr benötigt mit den 10 Produkten pro Invoice"""
    #     strapi_resp: dict = get_by_id_from_strapi(endpoint=STRAPI_INVOICE_ENDP,
    #                                               add_filter=os.getenv('STRAPI_GET_ALL_INVOICE_PRODUCTNAMES_FILTER'),
    #                                               bearer_token=bearer_token,
    #                                               entry_id=invoice_id)
    #     product_count: int = len(strapi_resp["data"]["attributes"]["products"]["data"])
    #
    #     """die get template function muss im Bezug auf random abgeändert werden.
    #        Sie darf den Product count nicht mehr mit einbeziehen."""
    #     template_data = get_template_from_strapi(bearer_token=bearer_token, template_id=template_id,
    #                                              template_endp=os.getenv('STRAPI_TEMPLATE_ENDP'),
    #                                              count_of_products=product_count,
    #                                              random=True)
    # else:

    configurator = HtmlConfigurator(
        invoices_used=json.loads(invoices_used),
        templates_used=json.loads(templates_used),
        specific_product_nums=json.loads(specific_product_nums),
        languages_used=json.loads(languages_used),
    )
    detailed_combinations: list[dict] = configurator.detailed_combinations()
    all_pdf_ids: list[int] = []
    for combination in detailed_combinations:
        template_data = get_template_from_strapi(
            bearer_token=bearer_token,
            template_id=combination["templateID"],
            template_endp=STRAPI_TEMPLATE_ENDP,
        )
        adapter = Invoice_Adpater(
            data=None,
            html_template_data=[*template_data],
            html_placeholder=HTMLPlaceholders,
            bearer_token=bearer_token,
        )
        pdf_invoice_id: int = adapter.create_pdf_invoice_entry(entry_id=combination["invoiceID"])
        all_pdf_ids.append(pdf_invoice_id)

    return {"pdf_invoice_id": all_pdf_ids}


@app.post("/create_pdf_for_pdf_invoice_entry")
async def create_pdf(
    pdf_invoice_id: int = Form(...),
    bearer_token: str = Form(...),
    pdf_params: str = Form(...),
    # None bedeutet nimmt defaults,  3.07.2024: wenn es bei headless Browser rendering bleibt braucht man das nicht mehr.
) -> JSON:
    """
    Creates the PDF from the HTML saved in strapi with the specific pdf_invoice_id

    :param pdf_invoice_id: ID of the pdf_invoice
    :param bearer_token: Strapi bearer token
    :param pdf_params: Parameters for the creation of the PDF ( 25.07.2024 currently just dummy)
    :return: Gives back the id of the pdf_invoice entry again (in which the pdf is now stored).
    """
    try:
        pdf_params = json.loads(pdf_params)
    except Exception as e:
        pdf_params = {}
        print(e)
    adapter = Invoice_Adpater(data=None, bearer_token=bearer_token)

    pdf_invoice_id: int = await adapter.create_pdf(
        pdf_invoice_id=pdf_invoice_id,
        pdf_output_name="src/Strapi/temporary.pdf",
    )

    return {"pdf_invoice_id": pdf_invoice_id}


@app.get("/create_template")
async def create_template(
    openai_key: str,
) -> str:
    """Create a new template (placeholder implementation)."""
    template: str = ""
    return template


@app.post("/create_rawHTML")
async def create_rawHTML(
    file: UploadFile = File(...),
    name: str = Form(...),
    description: str = Form(...),
    doctype: str = Form(...),
    detect_vertical_text: bool = True,
    text_in_images: bool = False,
    save_embd_imgs: bool = False,
    image_dir: str = "",
    metadata: JSON | None = None,
    products: int = 10,
    language: str = "german",
) -> JSON:
    """
    Creates the rawHTML of a give PDF-File.
    :param file: PDF File
    :param name: User Input: Name of the document
    :param description: User Input: Description of the document
    :param doctype: User Input: type of the document
    :param metadata: Various metadata, such as the dimensions of the document title, author description,
                         margin, overflow, background color, padding. None leads to decent defaults.
    :param detect_vertical_text:  Recognition of vertical text
    :param text_in_images: Recognition of text in images
    :param save_embd_imgs: Save found images
    :param image_dir: Storage location of the images found
    :param products: Number of products in the template, Default,10
    :param language: Language of the document. Default, german
    :return: dict with the raw HTML as string
    """

    # Process the file or perform your logic here
    # Read the content of the file
    print("name", name)
    print("description", description)
    print("doctype", doctype)
    """---Logik der HTML Erstellung---"""
    pdf_IOb: BytesIO = BytesIO(await file.read())
    if metadata is None:
        metadata = {}

    item_extractor = LTItemExtractor(
        pdf_path_or_bytes_io=pdf_IOb,
        detect_vertical_text=detect_vertical_text,
        text_in_images=text_in_images,
        save_embd_imgs=save_embd_imgs,
        image_directory=image_dir,
    )
    html_converter = LTItemsToHtmlConverter()
    html_string: str = await html_converter.gen_html_from_lt_items(
        lt_items=item_extractor.return_lt_list(), metadata=metadata
    )
    item_extractor.reset_lt_list()
    # html = BeautifulSoup(html_string, "html.parser")
    pprint(html_string)
    """--------------------------------"""
    strapi_url = f"{os.getenv('STRAPI_URL')}{STRAPI_TEMPLATE_ENDP}"
    payload = {
        "data": {
            "name": name,
            "description": description,
            "doctype": doctype,
            "html": html_string,
            "language": language,
            "products": products,
        }
    }

    headers = {
        "Authorization": f"Bearer {os.getenv('STRAPI_BEARER_TOKEN')}",
        "Content-Type": "application/json",
    }

    response = requests.post(strapi_url, json=payload, headers=headers)
    print(response)
    return response.json()


@app.post("/create_entity_json_from_rawHTML")
async def create_entity_json_from_rawHTML(
    html: str = Form(...),
    openaiKey: str = Form(...),
) -> JSON:
    """
    Creates a JSON File filled with the entities found in the given html.
    :param html: HTML from which the entities should be identified
    :param openaiKey:  OpenAI key
    :return: JSON with all the entities of the html.
    """
    template_generator = HtmlToTemplateConverter(
        html=html,
        open_ai_key=openaiKey,  # Fixed: Use provided key instead of hardcoded
    )

    return template_generator.identify_entities_and_persons()


@app.post("/create_template_from_rawHTML_and_entities")
async def create_template_from_rawHTML_and_entities(
    html: str = Form(...), entities: str = Form(...)
) -> JSON:
    """
    Replaces the entities in the html file with specific placeholders to create a universal template
    :param html:  HTML where the entities come from
    :param entities: Entities of the html
    :return: template
    """
    entities_dict: JSON = json.loads(entities)
    print(entities_dict)
    template_generator = HtmlToTemplateConverter(html=html, open_ai_key="PLACEHOLDER")
    html_w_pl: str = template_generator.replace_entities_n_persons(
        placeholder_w_entity_n_persons=entities_dict
    )
    return {"Template": html_w_pl}


@app.post("/modify_template_product_count")
async def modify_template_product_count(
    html_template: str, product_count: int, openai_key: str
) -> JSON:
    """
    25.07.2024: IS this actually used? Product count is made by hand in the App.
    The idea is to create a template with any product count wanted.

    :param html_template:  Universal template
    :param product_count: Number of products
    :param openai_key: OpenAI key
    :return: Template with modified product count
    """
    modifier = TemplateModifier(openai_key=openai_key)
    prompt: str = Template_Modifier_Prompt(html=html_template).get_modify_product_count_prompt(
        product_count=product_count
    )

    return {"modified_template": modifier.modify_given_html(prompt=prompt)}


@app.post("/retrieve_html_placeholders")
async def retrieve_html_placeholders() -> JSON:
    """
    Gives back the placeholders. Used to replace the entities in the html to create a template.
    :return: placeholders
    """
    # adapter = Invoice_Adpater()  # Unused
    return {"Placeholders": HTMLPlaceholders_frontend}


@app.post("/extract_text_from_html")
async def extract_text_from_html(html: str = Form(...)) -> JSON:
    """
    Extract the text part of the html
    :param html: html from which the text is to be extracted
    :return:  only the text, without head etc. from the html
    """
    soup = BeautifulSoup(html, "html.parser")
    text: str = soup.get_text()
    return {"HTML_text": text}


@app.post("/get_html_count")
async def get_html_count(
    invoices_used: str = Form(...),
    templates_used: str = Form(...),
    specific_product_nums: str = Form(...),
    languages_used: str = Form(...),
) -> JSON:
    """
    The final number of invoices (html of the invoices) which would be created by choosing this specific
    input parameters.
    :param invoices_used: Number of invoice data to be used
    :param templates_used: Number of templates to be used
    :param specific_product_nums: Number of products allowed in the invoices
    :param languages_used: Number of languages to be used
    :return: Final number of invoices (html of the invoices) you get from the chosen input parameters.
    """
    configurator = HtmlConfigurator(
        invoices_used=json.loads(invoices_used),
        templates_used=json.loads(templates_used),
        specific_product_nums=json.loads(specific_product_nums),
        languages_used=json.loads(languages_used),
    )

    return {"htmlCount": configurator.calculate_html_number()}


@app.post("/get_detailed_combinations")
async def get_detailed_combinations(
    invoices_used: str = Form(...),
    templates_used: str = Form(...),
    specific_product_nums: str = Form(...),
    languages_used: str = Form(...),
) -> JSON:
    """
    Get the ids of the individual parameters for every combination of the input parameters. The info is then used to
    precisely create the htmls of the invoices.

    :param invoices_used: Number of invoice data to be used
    :param templates_used: Number of templates to be used
    :param specific_product_nums: Number of products allowed in the invoices
    :param languages_used: Number of languages to be used
    :return: The detailed combinations of the input parameters used for the creation of the htmls of the invoices
    """
    configurator = HtmlConfigurator(
        invoices_used=json.loads(invoices_used),
        templates_used=json.loads(templates_used),
        specific_product_nums=json.loads(specific_product_nums),
        languages_used=json.loads(languages_used),
    )

    return {"detailed_combinations": configurator.detailed_combinations()}


@app.post("/import_json_invoice")
async def import_json_invoice(
    bearer_token: str = Form(...),
    json_path: str = Form(None),
    invoice_data: str = Form(None),
) -> JSON:
    """
    Import an invoice from a JSON file or JSON string directly into Strapi.
    Much faster than LLM generation - uses pre-generated invoice data.

    :param bearer_token: Strapi bearer token
    :param json_path: Path to JSON file (optional, if not provided use invoice_data)
    :param invoice_data: JSON string of invoice data (optional, if not provided use json_path)
    :return: ID of the created invoice
    """
    try:
        if json_path:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        elif invoice_data:
            data = json.loads(invoice_data)
        else:
            return {"error": "Either json_path or invoice_data must be provided"}

        adapter = Invoice_Adpater(data=data, bearer_token=bearer_token)
        created_invoice_id = adapter.post_all_available_data()
        return {"invoice_id": created_invoice_id, "status": "success"}
    except Exception as e:
        print(f"Error importing invoice: {str(e)}")
        return {"error": str(e)}


@app.get("/import_batch_invoices")
async def import_batch_invoices(
    bearer_token: str,
    folder_path: str = "gen_data/invoices_141_fixed_v4/json",
    count: int = 5,
) -> JSON:
    """
    Import multiple invoices from a folder of JSON files.

    :param bearer_token: Strapi bearer token
    :param folder_path: Path to folder containing JSON invoice files
    :param count: Number of invoices to import (default 5)
    :return: List of created invoice IDs
    """
    import glob

    try:
        # Get list of JSON files
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        full_path = os.path.join(base_path, folder_path)
        json_files = sorted(glob.glob(os.path.join(full_path, "invoice_*.json")))[:count]

        created_ids = []
        errors = []

        for json_file in json_files:
            try:
                with open(json_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)

                adapter = Invoice_Adpater(data=data, bearer_token=bearer_token)
                invoice_id = adapter.post_all_available_data()
                created_ids.append({"file": os.path.basename(json_file), "invoice_id": invoice_id})
            except Exception as e:
                errors.append({"file": os.path.basename(json_file), "error": str(e)})

        return {
            "imported": len(created_ids),
            "invoice_ids": created_ids,
            "errors": errors if errors else None
        }
    except Exception as e:
        return {"error": str(e)}


@app.get("/list_available_json_invoices")
async def list_available_json_invoices(
    folder_path: str = "gen_data/invoices_141_fixed_v4/json",
) -> JSON:
    """
    List available JSON invoice files that can be imported.

    :param folder_path: Path to folder containing JSON invoice files
    :return: List of available JSON files
    """
    import glob

    try:
        base_path = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        full_path = os.path.join(base_path, folder_path)
        json_files = sorted(glob.glob(os.path.join(full_path, "invoice_*.json")))

        return {
            "folder": folder_path,
            "count": len(json_files),
            "files": [os.path.basename(f) for f in json_files[:50]],  # Limit to first 50
            "total_available": len(json_files)
        }
    except Exception as e:
        return {"error": str(e)}


@app.post("/generate_logo")
async def generate_logo(
    company_name: str = Form(...),
    industry: str = Form(default="general business"),
    force_regenerate: bool = Form(default=False),
    provider: str = Form(default="openai"),
) -> JSON:
    """
    Generate a company logo using AI and return as base64.
    Logos are cached to avoid regenerating the same logo.

    :param company_name: Name of the company
    :param industry: Industry/sector description (optional)
    :param force_regenerate: Force regeneration even if cached (optional)
    :param provider: AI provider to use - 'openai' or 'gemini' (optional, default: openai)
    :return: Base64 encoded logo image
    """
    from src.LogoGenerator import LogoGenerator

    try:
        generator = LogoGenerator(provider_type=provider)
        logo_base64 = generator.generate_logo_base64(
            company_name=company_name,
            industry=industry,
            force_regenerate=force_regenerate
        )

        return {
            "success": True,
            "company_name": company_name,
            "logo_base64": f"data:image/png;base64,{logo_base64}",
            "from_cache": not force_regenerate,
            "provider": provider
        }
    except Exception as e:
        return {"error": str(e), "success": False}


@app.get("/get_cached_logos")
async def get_cached_logos() -> JSON:
    """
    Get list of all cached logos.

    :return: List of cached logo cache keys
    """
    from src.LogoGenerator import LogoGenerator

    try:
        openai_key = os.getenv("OPENAI_API_KEY", "dummy")
        generator = LogoGenerator(openai_key=openai_key)
        cached = generator.get_cached_logos()

        return {
            "count": len(cached),
            "cache_keys": list(cached.keys())
        }
    except Exception as e:
        return {"error": str(e)}


@app.post("/generate_and_upload_logo")
async def generate_and_upload_logo(
    pdf_invoice_id: int = Form(...),
    company_name: str = Form(...),
    industry: str = Form(default="general business"),
    style_prompt: str = Form(default="minimalistic, clean white background, featuring the company name or initials"),
    bearer_token: str = Form(...),
    force_regenerate: str = Form(default="false"),  # String from FormData, convert below
    provider: str = Form(default="openai"),
) -> JSON:
    """
    Generate a company logo using AI and upload to Strapi Media Library.
    Links the logo to the specified pdf_invoice entry.

    :param pdf_invoice_id: ID of the pdf_invoice entry
    :param company_name: Name of the company
    :param industry: Industry/sector description
    :param bearer_token: Strapi bearer token
    :param force_regenerate: Force regeneration even if cached
    :param provider: AI provider to use - 'openai' or 'gemini' (optional, default: openai)
    :return: Media ID and URL of the uploaded logo
    """
    from src.LogoGenerator import LogoGenerator
    from src.Requests.Request_strapi import post_to_strapi_with_id_response, put_to_strapi
    from src.utility.strapi_endpoints import STRAPI_MEDIA_LIBRARY_ENDP, STRAPI_PDFINVOICE_ENDP

    # Convert string to boolean
    should_regenerate = force_regenerate.lower() in ("true", "1", "yes")
    print(f"Logo generation request: company={company_name}, provider={provider}, force_regenerate={should_regenerate}")

    try:
        # Generate logo using specified provider
        generator = LogoGenerator(provider_type=provider)
        logo_bytes = generator.generate_logo(
            company_name=company_name,
            industry=industry,
            style_prompt=style_prompt,
            force_regenerate=should_regenerate
        )

        # Convert to base64 for direct embedding in HTML
        import base64
        logo_base64 = base64.b64encode(logo_bytes).decode('utf-8')
        logo_data_url = f"data:image/png;base64,{logo_base64}"

        return {
            "success": True,
            "mediaId": 0,  # No media ID since we're using base64
            "logoUrl": logo_data_url,
            "companyName": company_name,
            "fromCache": not should_regenerate,
            "provider": provider
        }
    except Exception as e:
        print(f"Error generating/uploading logo: {str(e)}")
        return {"error": str(e), "success": False}


@app.post("/upload_logo")
async def upload_logo(
    pdf_invoice_id: int = Form(...),
    bearer_token: str = Form(...),
    file: UploadFile = File(...),
) -> JSON:
    """
    Upload a user-provided logo image and return as base64.

    :param pdf_invoice_id: ID of the pdf_invoice entry
    :param bearer_token: Strapi bearer token
    :param file: Logo image file (PNG, JPG, SVG)
    :return: Base64 data URL of the uploaded logo
    """
    import base64

    try:
        # Validate file type
        allowed_types = ["image/png", "image/jpeg", "image/jpg", "image/svg+xml"]
        if file.content_type not in allowed_types:
            return {
                "error": f"Invalid file type. Allowed: {allowed_types}",
                "success": False
            }

        # Read file content
        file_content = await file.read()

        # Convert to base64 for direct embedding in HTML
        logo_base64 = base64.b64encode(file_content).decode('utf-8')
        mime_type = file.content_type or "image/png"
        logo_data_url = f"data:{mime_type};base64,{logo_base64}"

        return {
            "success": True,
            "mediaId": 0,
            "logoUrl": logo_data_url,
            "filename": file.filename,
        }
    except Exception as e:
        print(f"Error uploading logo: {str(e)}")
        return {"error": str(e), "success": False}


@app.post("/delete_logo")
async def delete_logo(
    pdf_invoice_id: int = Form(...),
    bearer_token: str = Form(...),
) -> JSON:
    """
    Remove logo from pdf_invoice entry and delete from media library.

    :param pdf_invoice_id: ID of the pdf_invoice entry
    :param bearer_token: Strapi bearer token
    :return: Success status
    """
    from src.Requests.Request_strapi import put_to_strapi, delete_from_strapi
    from src.utility.strapi_endpoints import STRAPI_MEDIA_LIBRARY_ENDP, STRAPI_PDFINVOICE_ENDP

    try:
        # First get the current logo media ID
        logo_response = get_by_id_from_strapi(
            endpoint=STRAPI_PDFINVOICE_ENDP,
            bearer_token=bearer_token,
            entry_id=pdf_invoice_id,
            add_filter="?populate=logo",
        )

        media_id = None
        if logo_response.get("data", {}).get("attributes", {}).get("logo", {}).get("data"):
            media_id = logo_response["data"]["attributes"]["logo"]["data"]["id"]

        # Remove logo reference from pdf_invoice
        put_to_strapi(
            endpoint=STRAPI_PDFINVOICE_ENDP,
            index=pdf_invoice_id,
            data={"data": {"logo": None}},
            bearer_token=bearer_token,
        )

        # Delete from media library if exists
        if media_id:
            try:
                delete_from_strapi(
                    endpoint=STRAPI_MEDIA_LIBRARY_ENDP,
                    entry_id=media_id,
                    bearer_token=bearer_token,
                )
            except Exception as delete_error:
                print(f"Warning: Could not delete logo from media library: {delete_error}")

        return {
            "success": True,
            "deletedMediaId": media_id
        }
    except Exception as e:
        print(f"Error deleting logo: {str(e)}")
        return {"error": str(e), "success": False}


@app.post("/wizard/generate_invoice")
async def wizard_generate_invoice(
    bearer_token: str = Form(...),
    prompt: str = Form(None),
    language: str = Form("de"),
    product_count: int = Form(5),
) -> JSON:
    """
    Generate an invoice for the dataset builder wizard.
    Picks a random validated template and generates invoice data.

    :param bearer_token: Strapi bearer token
    :param openai_key: OpenAI API key
    :param prompt: Optional custom prompt for generation (None = random)
    :param language: Invoice language (de/en)
    :param product_count: Number of products (1-50)
    :return: pdf_id and pdf_url of the created invoice
    """
    import random
    import httpx

    try:
        # Step 1: Get a random validated template
        async with httpx.AsyncClient(timeout=30.0) as client:
            templates_response = await client.get(
                f"{os.getenv('STRAPI_URL')}{STRAPI_TEMPLATE_ENDP}",
                headers={"Authorization": f"Bearer {bearer_token}"},
                params={
                    "filters[validated][$eq]": "true",
                    "pagination[limit]": 100,
                    "fields[0]": "id",
                    "fields[1]": "name",
                    "fields[2]": "products",
                },
            )

            if templates_response.status_code != 200:
                return {"error": f"Failed to fetch templates: {templates_response.text}", "success": False}

            templates_data = templates_response.json()
            templates = templates_data.get("data", [])

            if not templates:
                return {"error": "No validated templates found", "success": False}

            # Pick random template
            selected_template = random.choice(templates)
            template_id = selected_template["id"]
            template_product_count = selected_template.get("attributes", {}).get("products", 10)

        # Step 2: Generate invoice data
        generator = InvoiceGenerator(
            model="gpt-5.1",
            temperature=0.8,
            product_count=min(product_count, template_product_count),
            time_limit=30000,
            invoice_lang=language,
            openai_key=os.getenv("OPENAI_API_KEY"),
            bearer_token=bearer_token,
        )

        invoice_data = generator.generate_invoice_data(
            w_fict_company=True,
            all_content_w_llm=False,
        )

        # Step 3: Post invoice data to Strapi
        adapter = Invoice_Adpater(data=invoice_data, bearer_token=bearer_token)
        invoice_id = adapter.post_all_available_data()

        # Step 4: Get template data and create pdf_invoice entry
        template_data = get_template_from_strapi(
            bearer_token=bearer_token,
            template_id=template_id,
            template_endp=STRAPI_TEMPLATE_ENDP,
        )

        adapter2 = Invoice_Adpater(
            data=None,
            html_template_data=[*template_data],
            html_placeholder=HTMLPlaceholders,
            bearer_token=bearer_token,
        )
        pdf_invoice_id = adapter2.create_pdf_invoice_entry(entry_id=invoice_id)

        # Step 5: Generate the PDF
        adapter3 = Invoice_Adpater(data=None, bearer_token=bearer_token)
        await adapter3.create_pdf(
            pdf_invoice_id=pdf_invoice_id,
            pdf_output_name="src/Strapi/temporary.pdf",
        )

        # Step 6: Get PDF URL
        pdf_response = get_by_id_from_strapi(
            endpoint=STRAPI_PDFINVOICE_ENDP,
            bearer_token=bearer_token,
            entry_id=pdf_invoice_id,
            add_filter=STRAPI_ONLY_URL_OF_PDF_FILTER,
        )

        # Safely extract PDF URL with proper null checking
        pdf_data = pdf_response.get("data", {})
        pdf_attrs = pdf_data.get("attributes", {}) if pdf_data else {}
        pdf_relation = pdf_attrs.get("pdf", {}) if pdf_attrs else {}
        pdf_inner_data = pdf_relation.get("data") if pdf_relation else None

        if pdf_inner_data is None:
            return {
                "success": False,
                "error": "PDF generation failed - PDF was not properly linked to the invoice entry",
                "pdf_id": pdf_invoice_id,
                "invoice_id": invoice_id,
            }

        pdf_url = os.getenv("STRAPI_URL") + pdf_inner_data.get("attributes", {}).get("url", "")

        return {
            "success": True,
            "pdf_id": pdf_invoice_id,
            "pdf_url": pdf_url,
            "invoice_id": invoice_id,
            "template_id": template_id,
            "template_name": selected_template.get("attributes", {}).get("name", "Unknown"),
        }

    except Exception as e:
        print(f"Error in wizard invoice generation: {str(e)}")
        return {"error": str(e), "success": False}


@app.get("/wizard/random_template")
async def wizard_get_random_template(
    bearer_token: str,
) -> JSON:
    """
    Get a random validated template for preview in the wizard.

    :param bearer_token: Strapi bearer token
    :return: Template info including preview image URL
    """
    import random
    import httpx

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            templates_response = await client.get(
                f"{os.getenv('STRAPI_URL')}{STRAPI_TEMPLATE_ENDP}",
                headers={"Authorization": f"Bearer {bearer_token}"},
                params={
                    "filters[validated][$eq]": "true",
                    "pagination[limit]": 100,
                    "populate": "preview_image",
                },
            )

            if templates_response.status_code != 200:
                return {"error": f"Failed to fetch templates: {templates_response.text}", "success": False}

            templates_data = templates_response.json()
            templates = templates_data.get("data", [])

            if not templates:
                return {"error": "No validated templates found", "success": False}

            # Pick random template
            selected = random.choice(templates)
            attrs = selected.get("attributes", {})

            preview_url = None
            if attrs.get("preview_image", {}).get("data"):
                preview_url = os.getenv("STRAPI_URL") + attrs["preview_image"]["data"]["attributes"]["url"]

            return {
                "success": True,
                "template": {
                    "id": selected["id"],
                    "name": attrs.get("name", "Unknown"),
                    "description": attrs.get("description", ""),
                    "products": attrs.get("products", 10),
                    "language": attrs.get("language", "german"),
                    "preview_url": preview_url,
                }
            }

    except Exception as e:
        print(f"Error fetching random template: {str(e)}")
        return {"error": str(e), "success": False}


@app.post("/crop_pdf")
async def crop_pdf(
    pdf_invoice_id: int = Form(...),
    x_percent: float = Form(...),
    y_percent: float = Form(...),
    width_percent: float = Form(...),
    height_percent: float = Form(...),
) -> JSON:
    """
    Crop a PDF to the specified region and update it in Strapi.

    :param pdf_invoice_id: ID of the pdf_invoice entry
    :param x_percent: Left edge of crop region as percentage (0-100)
    :param y_percent: Top edge of crop region as percentage (0-100)
    :param width_percent: Width of crop region as percentage (0-100)
    :param height_percent: Height of crop region as percentage (0-100)
    :return: Success status
    """
    import fitz  # PyMuPDF
    import tempfile

    bearer_token = os.getenv("STRAPI_BEARER_TOKEN")

    try:
        # Get the PDF from Strapi
        pdf_data = get_by_id_from_strapi(
            endpoint=STRAPI_PDFINVOICE_ENDP,
            bearer_token=bearer_token,
            entry_id=pdf_invoice_id,
            add_filter="?populate=pdf",
        )

        pdf_url = pdf_data.get("data", {}).get("attributes", {}).get("pdf", {}).get("data", {}).get("attributes", {}).get("url")
        pdf_media_id = pdf_data.get("data", {}).get("attributes", {}).get("pdf", {}).get("data", {}).get("id")

        if not pdf_url:
            return {"success": False, "error": "No PDF found for this invoice"}

        # Download the PDF
        full_url = os.getenv("STRAPI_URL") + pdf_url
        response = requests.get(full_url)
        if response.status_code != 200:
            return {"success": False, "error": "Failed to download PDF"}

        # Open PDF with PyMuPDF
        pdf_bytes = BytesIO(response.content)
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")

        if len(doc) == 0:
            return {"success": False, "error": "PDF has no pages"}

        page = doc[0]
        page_rect = page.rect

        # Calculate crop box in PDF coordinates
        x = page_rect.width * (x_percent / 100)
        y = page_rect.height * (y_percent / 100)
        w = page_rect.width * (width_percent / 100)
        h = page_rect.height * (height_percent / 100)

        # Create crop rectangle
        crop_rect = fitz.Rect(x, y, x + w, y + h)

        # IMPORTANT: Actually render the cropped region to create a new PDF
        # (set_cropbox only sets metadata which pdf2image ignores)
        # Render at high resolution for quality
        zoom = 3  # 3x zoom for high quality
        mat = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=mat, clip=crop_rect)

        # Create a new PDF with just the cropped content
        new_doc = fitz.open()
        # Create page with cropped dimensions (at 72 DPI base)
        new_page = new_doc.new_page(width=crop_rect.width, height=crop_rect.height)

        # Insert the cropped image into the new page
        img_rect = fitz.Rect(0, 0, crop_rect.width, crop_rect.height)
        new_page.insert_image(img_rect, pixmap=pix)

        # Save to temporary file
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp_file:
            tmp_path = tmp_file.name
            new_doc.save(tmp_path)

        new_doc.close()
        doc.close()

        # Upload the cropped PDF to Strapi media library (without ref/refId/field - we'll link manually)
        upload_url = f"{os.getenv('STRAPI_URL')}/api/upload"
        with open(tmp_path, "rb") as f:
            files = {"files": (f"cropped_{pdf_invoice_id}.pdf", f, "application/pdf")}
            upload_response = requests.post(
                upload_url,
                files=files,
                headers={"Authorization": f"Bearer {bearer_token}"}
            )

        # Clean up temp file
        os.remove(tmp_path)

        if upload_response.status_code not in [200, 201]:
            return {"success": False, "error": f"Failed to upload cropped PDF: {upload_response.text}"}

        # Extract the new file ID and URL from upload response
        upload_data = upload_response.json()
        new_file_id = None
        new_url = None
        if isinstance(upload_data, list) and len(upload_data) > 0:
            new_file_id = upload_data[0].get("id")
            new_url = upload_data[0].get("url")
        elif isinstance(upload_data, dict):
            new_file_id = upload_data.get("id")
            new_url = upload_data.get("url")

        if not new_file_id:
            return {"success": False, "error": "Failed to get new file ID from upload response"}

        print(f"[CROP DEBUG] Old PDF media ID: {pdf_media_id}")
        print(f"[CROP DEBUG] New file ID: {new_file_id}")
        print(f"[CROP DEBUG] New URL: {new_url}")

        # Explicitly update the pdf-invoice entry to link to the new file
        update_url = f"{os.getenv('STRAPI_URL')}/api/pdf-invoices/{pdf_invoice_id}"
        print(f"[CROP DEBUG] Updating pdf-invoice at: {update_url}")
        update_response = requests.put(
            update_url,
            json={"data": {"pdf": new_file_id}},
            headers={
                "Authorization": f"Bearer {bearer_token}",
                "Content-Type": "application/json"
            }
        )
        print(f"[CROP DEBUG] Update response status: {update_response.status_code}")
        print(f"[CROP DEBUG] Update response body: {update_response.text[:500]}")

        if update_response.status_code not in [200, 201]:
            return {"success": False, "error": f"Failed to update pdf-invoice relation: {update_response.text}"}

        # Verify the update worked by fetching the entry again
        verify_response = get_by_id_from_strapi(
            endpoint=STRAPI_PDFINVOICE_ENDP,
            bearer_token=bearer_token,
            entry_id=pdf_invoice_id,
            add_filter="?populate=pdf",
        )
        verify_pdf_id = verify_response.get("data", {}).get("attributes", {}).get("pdf", {}).get("data", {}).get("id")
        verify_pdf_url = verify_response.get("data", {}).get("attributes", {}).get("pdf", {}).get("data", {}).get("attributes", {}).get("url")
        print(f"[CROP DEBUG] After update - PDF ID: {verify_pdf_id}, URL: {verify_pdf_url}")

        # Delete old PDF from Strapi media library (after successful update)
        if pdf_media_id and pdf_media_id != new_file_id:
            delete_url = f"{os.getenv('STRAPI_URL')}/api/upload/files/{pdf_media_id}"
            delete_response = requests.delete(
                delete_url,
                headers={"Authorization": f"Bearer {bearer_token}"}
            )
            print(f"[CROP DEBUG] Delete old file response: {delete_response.status_code}")

        return {"success": True, "message": "PDF cropped successfully", "new_url": new_url}

    except Exception as e:
        print(f"Error cropping PDF: {str(e)}")
        return {"success": False, "error": str(e)}
