"""------------------------------------------------------------------------------------------------------------------"""

from src.types import JSON

"""HTML Placeholders: Placeholders for the EntityPreviewer in the docgen-workbench
                      that are to be replaced by the equivalents of the json output

"""

"""------------------------------------------------------------------------------------------------------------------"""
"""keys heissen (bis auf derzeit: adresse und citywplc, die separat erstellt werden) wie die Parameter in Strapi
   Die Übereinstimmung des Namens ist essentiell für das Mapping von Inhalt in Strapi mit dem Namen und dem zugeordneten
   value in HTML_Placeholders für die keys."""

HTMLPlaceholders_frontend: JSON = {
    "buyer": {
        "address": "{buyer_address}",
        "street": "{buyer_street}",
        "city": "{buyer_city}",
        "citywplc": "{buyer_citywplc}",
        "name": "{buyer_name}",
        "employee": "{buyer_employee}",
        "email": "{buyer_email}",
        "website": "{buyer_website}",
        "phone": "{buyer_phone}",
        "fax": "{buyer_fax}",
        "iban": "{buyer_iban}",
        "bic": "{buyer_bic}",
        "ifforeigntaxidentifier": "{buyer_ifforeigntaxidentifier}",
        "customerid": "{buyer_customerid}",
        "account_num": "{buyer_account_number}",
    },
    "seller": {
        "address": "{seller_address}",
        "street": "{seller_street}",
        "city": "{seller_city}",
        "citywplc": "{seller_citywplc}",
        "name": "{seller_name}",
        "employee": "{seller_employee}",
        "email": "{seller_email}",
        "website": "{seller_website}",
        "phone": "{seller_phone}",
        "fax": "{seller_fax}",
        "iban": "{seller_iban}",
        "bic": "{seller_bic}",
        "taxidentifier": "{seller_taxidentifier}",
    },
    "products": {
        "name1": "{product_name_1}",
        "price1": "{product_price_1}",
        "unity1": "{product_unity_1}",
        "quantity1": "{product_quantity_1}",
        "taxrate1": "{product_sales_tax_percent_1}",
        "tax1": "{product_sales_tax_cost_1}",
        "product_cost1": "{product_cost_wo_tax_1}",
        "product_cost_w_tax1": "{product_cost_w_tax_1}",
        "transport_cost1": "{product_transport_cost_1}",
        "position1": "{product_pos_1}",
        "number1": "{product_num_1}",
        "name2": "{product_name_2}",
        "price2": "{product_price_2}",
        "unity2": "{product_unity_2}",
        "quantity2": "{product_quantity_2}",
        "taxrate2": "{product_sales_tax_percent_2}",
        "tax2": "{product_sales_tax_cost_2}",
        "product_cost2": "{product_cost_wo_tax_2}",
        "product_cost_w_tax2": "{product_cost_w_tax_2}",
        "transport_cost2": "{product_transport_cost_2}",
        "position2": "{product_pos_2}",
        "number2": "{product_num_2}",
        "name3": "{product_name_3}",
        "price3": "{product_price_3}",
        "unity3": "{product_unity_3}",
        "quantity3": "{product_quantity_3}",
        "taxrate3": "{product_sales_tax_percent_3}",
        "tax3": "{product_sales_tax_cost_3}",
        "product_cost3": "{product_cost_wo_tax_3}",
        "product_cost_w_tax3": "{product_cost_w_tax_3}",
        "transport_cost3": "{product_transport_cost_3}",
        "position3": "{product_pos_3}",
        "number3": "{product_num_3}",
        "name4": "{product_name_4}",
        "price4": "{product_price_4}",
        "unity4": "{product_unity_4}",
        "quantity4": "{product_quantity_4}",
        "taxrate4": "{product_sales_tax_percent_4}",
        "tax4": "{product_sales_tax_cost_4}",
        "product_cost4": "{product_cost_wo_tax_4}",
        "product_cost_w_tax4": "{product_cost_w_tax_4}",
        "transport_cost4": "{product_transport_cost_4}",
        "position4": "{product_pos_4}",
        "number4": "{product_num_4}",
        "name5": "{product_name_5}",
        "price5": "{product_price_5}",
        "unity5": "{product_unity_5}",
        "quantity5": "{product_quantity_5}",
        "taxrate5": "{product_sales_tax_percent_5}",
        "tax5": "{product_sales_tax_cost_5}",
        "product_cost5": "{product_cost_wo_tax_5}",
        "product_cost_w_tax5": "{product_cost_w_tax_5}",
        "transport_cost5": "{product_transport_cost_5}",
        "position5": "{product_pos_5}",
        "number5": "{product_num_5}",
        "name6": "{product_name_6}",
        "price6": "{product_price_6}",
        "unity6": "{product_unity_6}",
        "quantity6": "{product_quantity_6}",
        "taxrate6": "{product_sales_tax_percent_6}",
        "tax6": "{product_sales_tax_cost_6}",
        "product_cost6": "{product_cost_wo_tax_6}",
        "product_cost_w_tax6": "{product_cost_w_tax_6}",
        "transport_cost6": "{product_transport_cost_6}",
        "position6": "{product_pos_6}",
        "number6": "{product_num_6}",
        "name7": "{product_name_7}",
        "price7": "{product_price_7}",
        "unity7": "{product_unity_7}",
        "quantity7": "{product_quantity_7}",
        "taxrate7": "{product_sales_tax_percent_7}",
        "tax7": "{product_sales_tax_cost_7}",
        "product_cost7": "{product_cost_wo_tax_7}",
        "product_cost_w_tax7": "{product_cost_w_tax_7}",
        "transport_cost7": "{product_transport_cost_7}",
        "position7": "{product_pos_7}",
        "number7": "{product_num_7}",
        "name8": "{product_name_8}",
        "price8": "{product_price_8}",
        "unity8": "{product_unity_8}",
        "quantity8": "{product_quantity_8}",
        "taxrate8": "{product_sales_tax_percent_8}",
        "tax8": "{product_sales_tax_cost_8}",
        "product_cost8": "{product_cost_wo_tax_8}",
        "product_cost_w_tax8": "{product_cost_w_tax_8}",
        "transport_cost8": "{product_transport_cost_8}",
        "position8": "{product_pos_8}",
        "number8": "{product_num_8}",
        "name9": "{product_name_9}",
        "price9": "{product_price_9}",
        "unity9": "{product_unity_9}",
        "quantity9": "{product_quantity_9}",
        "taxrate9": "{product_sales_tax_percent_9}",
        "tax9": "{product_sales_tax_cost_9}",
        "product_cost9": "{product_cost_wo_tax_9}",
        "product_cost_w_tax9": "{product_cost_w_tax_9}",
        "transport_cost9": "{product_transport_cost_9}",
        "position9": "{product_pos_9}",
        "number9": "{product_num_9}",
        "name10": "{product_name_10}",
        "price10": "{product_price_10}",
        "unity10": "{product_unity_10}",
        "quantity10": "{product_quantity_10}",
        "taxrate10": "{product_sales_tax_percent_10}",
        "tax10": "{product_sales_tax_cost_10}",
        "product_cost10": "{product_cost_wo_tax_10}",
        "product_cost_w_tax10": "{product_cost_w_tax_10}",
        "transport_cost10": "{product_transport_cost_10}",
        "position10": "{product_pos_10}",
        "number10": "{product_num_10}",
    },
    "general": {
        "dateofinvoice": "{dateofinvoice}",
        "dateofdeliveryorservice": "{dateofdeliveryorservice}",
        "invoicenumber": "{invoicenumber}",
        "subtotal": "{subtotal}",
        "taxes": "{taxes}",
        "total": "{total}",
        "total_transport_cost": "{total_transport_cost}",
        "contract_num": "{contract_number}",
        "random_number": "{random_number_id_sN&bN_wC_cP}",
    },
}

SpecialHTMLPlaceholders: list[JSON] = [
    {"address": "{buyer_address}"},
    {"citywplc": "{buyer_citywplc}"},
    {"address": "{seller_address}"},
    {"citywplc": "{seller_citywplc}"},
    {"total_transport_cost": "{total_transport_cost}"},
    {"account_num": "{buyer_account_number}"},
    {"contract_num": "{contract_number}"},
]
SpecialHTMLPlaceholders_Prods: list[JSON] = [
    {"product_cost": "{product_cost_wo_tax_}"},
    {"product_cost_w_tax": "{product_cost_w_tax_}"},
    {"transport_cost": "{product_transport_cost_}"},
    {"position": "{product_pos_}"},
    {"number": "{product_num_}"},
]
